spring:
  application:
    name: leolee-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#  instance:
#    statusPageUrlPath: ${server.servletPath}/info
server:
  port: 0
#    healthCheckUrlPath: ${server.servletPath}/health