
server:
  port: 8762
eureka:
  instance:
    hostname: leolee-2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://leolee-1:8761/eureka/,http://leolee-3:8763/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
spring:
  application:
    name: eureka-server