
server:
  port: 8761
eureka:
  instance:
    hostname: leolee-1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://leolee-2:8762/eureka/,http://leolee-3:8763/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
spring:
  application:
    name: eureka-server